export const NOTIFY_PROCESS_ERRORS = {
  REQUEST: "NOTIFY_PROCESS_RESPONSE_ERROR",
  RESPONSE: "NOTIFY_PROCESS_REQUEST_ERROR",
  AGGREGATE: "NOTIFY_PROCESS_RESPONSE_ERROR",
  UNKNOWN: "NOTIFY_PROCESS_UNKNOWN_ERROR",
};

export const NOTIFY_SEND_ERRORS = {
  REQUEST: "NOTIFY_SEND_RESPONSE_ERROR",
  RESPONSE: "NOTIFY_SEND_REQUEST_ERROR",
  AGGREGATE: "NOTIFY_SEND_RESPONSE_ERROR",
  UNKNOWN: "NOTIFY_SEND_UNKNOWN_ERROR",
};
