version: "3.9"
services:
  api:
    depends_on: [postgres]
    env_file:
      - api/.env
    build:
      context: .
      dockerfile: api/Dockerfile
  worker:
    depends_on: [postgres]
    environment:
      - NOTIFY_API_KEY=${NOTIFY_API_KEY:?}
    build:
      context: .
      dockerfile: worker/Dockerfile

  postgres:
    container_name: postgres
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: queue
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user