version: "3.9"
services:
  api:
    env_file:
      - api/.env
    build:
      context: .
      dockerfile: api/Dockerfile
  worker:
    environment:
      - NOTIFY_API_KEY=${NOTIFY_API_KEY:?}
    build:
      context: .
      dockerfile: worker/Dockerfile