export const SES_PROCESS_ERRORS = {
  REQUEST: "SES_PROCESS_REQUEST_ERROR",
  RESPONSE: "SES_PROCESS_RESPONSE_ERROR",
  AGGREGATE: "SES_PROCESS_AGGREGATE_ERROR",
  UNKNOWN: "SES_PROCESS_UNKNOWN_ERROR",
};

export const SES_SEND_ERRORS = {
  SES: "SES_SEND_SES_EXCEPTION",
  ON_COMPLETE: "SES_SEND_ON_COMPLETE",
};
